create trigger dbo.trigger3lapp on dbo.PEOPLE
AFTER INSERT, UPDATE
AS BEGIN
IF EXISTS(SELECT * FROM inserted WHERE BIRTHDAY>GETDATE())
BEGIN
RAISERROR ('Вы еще не родились',10,1);
ROLLBACK TRANSACTION;
END;
IF EXISTS(SELECT * FROM inserted WHERE (
BIRTHDAY<DATEADD(year, -100, GETDATE()) AND SEX LIKE '0')
OR (BIRTHDAY<DATEADD(year, -110, GETDATE()) AND SEX LIKE '1'))
BEGIN
RAISERROR ('Неправильная дата',10,1);
ROLLBACK TRANSACTION;
END;
END;
SET IDENTITY_INSERT dbo.PEOPLE ON ;
BEGIN TRANSACTION;