USE BestDatabaseBerkoz;
GO

SET NOCOUNT ON;

INSERT INTO REFACTIV (COD, NAME) VALUES ('0100', 'Сельское хозяйство, охота и связанная с этим деятельность по предоставлению услуг');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0110', 'Растениеводство: выращивание сельскохозяйственных культур; товарное овощеводство, садоводство');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0111', 'Выращивание зерновых культур');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0112', 'Выращивание овощных культур');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0113', 'Выращивание фруктов, орехов, культур для производства напитков и пряных культур');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0114', 'Выращивание масличных культур и культур для производства сахара');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0115', 'Выращивание растительных прядильных культур');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0116', 'Выращивание лекарственных культур');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0117', 'Выращивание кормовых культур');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0118', 'Специализированное садоводство и производство продуктов питомников');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0120', 'Животноводство');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0121', 'Разведение домашних животных');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0122', 'Производство продукции животноводства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0130', 'Выращивание культур в сочетании с разведением скота');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0140', 'Сельскохозяйственная деятельность по предоставлению услуг в области растениеводства и животноводства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0141', 'Предоставление услуг в области растениеводства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0142', 'Предоставление услуг в области животноводства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0150', 'Охота, промысел и разведение дичи; связанная с этим деятельность по предоставлению услуг');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0151', 'Охота и промысел дичи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0153', 'Предоставление услуг, связанных с охотой, промыслом и разведением дичи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0200', 'Лесоводство, лесозаготовки и связанная с этим деятельность по предоставлению услуг');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0210', 'Лесоводство');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0211', 'Сбор семян деревьев и кустарников');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0212', 'Выращивание сеянцев деревьев и кустарников');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0213', 'Выращивание саженцев деревьев и кустарников');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0220', 'Лесозаготовки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0230', 'Сбор дикорастущих лесных продуктов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0240', 'Предоставление услуг, относящихся к лесному хозяйству');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0500', 'Рыболовство, деятельность рыбопитомников и рыбных ферм; предоставление услуг, связанных с рыболовством');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0510', 'Рыболовство, деятельность рыбопитомников и рыбных ферм');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0511', 'Рыболовство');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0512', 'Промысел китов, дельфинов, ракообразных, моллюсков и добыча других морепродуктов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0513', 'Рыбоводство и выращивание водорослей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('0520', 'Предоставление услуг, связанных с рыболовством');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1000', 'Добыча каменного угля и лигнита; добыча торфа');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1010', 'Добыча и агломерация каменного угля');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1020', 'Добыча и агломерация лигнита (бурого угля)');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1030', 'Добыча и агломерация торфа и горючих сланцев');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1100', 'Добыча сырой нефти и природного газа; предоставление услуг, связанных с добычей нефти и газа');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1110', 'Добыча сырой нефти и природного газа');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1111', 'Добыча сырой нефти');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1112', 'Добыча природного газа');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1120', 'Предоставление услуг, связанных с добычей нефти и газа, кроме изыскательских работ');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1200', 'Добыча радиоактивных руд');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1300', 'Добыча металлических руд');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1310', 'Добыча железной руды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1320', 'Добыча руд цветных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1321', 'Добыча руд меди, никеля, кобальта, свинца, цинка, олова, хрома, вольфрама');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1322', 'Добыча алюминиевых руд');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1323', 'Добыча руд благородных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1329', 'Добыча руд щелочных, щелочноземельных, редкоземельных и прочих цветных металлов, кроме урановых и ториевых');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1400', 'Деятельность горнодобывающая и по разработке карьеров прочая');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1410', 'Разработка каменных, глиняных и песчаных карьеров');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1411', 'Добыча камня для строительства и памятников');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1412', 'Добыча гипса, ангидрита, мела, доломита, известняка');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1413', 'Добыча песка, гальки, гравия и щебня');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1414', 'Добыча глины');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1420', 'Деятельность горнодобывающая и по разработке карьеров, не включенная в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1421', 'Добыча минералов для химической промышленности и производства удобрений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1422', 'Добыча природной соли');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1500', 'Производство пищевых продуктов и напитков');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1510', 'Переработка и консервирование мяса, рыбы, фруктов, овощей, масел, жиров');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1511', 'Производство мяса и мясных продуктов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1512', 'Переработка и консервирование рыбы и рыбных продуктов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1513', 'Переработка фруктов и овощей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1514', 'Производство растительных и животных масел и жиров');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1520', 'Производство молочных продуктов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1530', 'Производство продуктов мукомольной промшленности, крахмалов, крахмальных продуктов и готовых кормов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1531', 'Производство продуктов мукомольной промышленности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1532', 'Производство крахмалов и крахмальных продуктов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1533', 'Производство готовых кормов для животных');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1540', 'Производство пищевых продуктов прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1541', 'Производство хлебобулочных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1542', 'Производство сахара');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1543', 'Производство какао, шоколада и кондитерских изделий из сахаристых');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1544', 'Производство макарон, лапши и аналогичных мучных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1550', 'Производство напитков');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1551', 'Дистилляция, ректификация и смешивание спиртных напитков; производство этилового спирта');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1552', 'Производство вин');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1553', 'Производство напитков из солода и производство солода');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1554', 'Производство безалкогольных напитков; разлив минеральных вод по бутылкам');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1600', 'Производство табака и табачных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1610', 'Производство табачных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1620', 'Производство табака');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1700', 'Производство текстильных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1710', 'Прядильное, ткацкое и отделочное производство');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1711', 'Подготовка и прядение текстильного волокна');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1712', 'Отделка тканей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1713', 'Изготовление готовых хлопчатобумажных тканей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1714', 'Изготовление готовых шерстяных тканей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1715', 'Изготовление готовых шелковых тканей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1716', 'Изготовление готовых тканей прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1717', 'Изготовление суровых тканей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1720', 'Производство текстильных изделий прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1721', 'Производство готовых текстильных изделий, кроме одежды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1722', 'Производство ковров и ковровых изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1723', 'Производство канатов, веревки, шпагата и сетного полотна');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1724', 'Производство галантерейных текстильных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1725', 'Производство войлока и нетканых тканей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1730', 'Производство трикотажных и вызаных тканей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1800', 'Производство одежды; выделка и крашение меха');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1810', 'Производство одежды, кроме одежды из натурального меха');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1811', 'Производство верхней одежды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1812', 'Производство белья');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1813', 'Производство спортивной одежды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1814', 'Производство предметов трикотажной и текстильной галантереи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1815', 'Производство головных уборов, кроме меховых');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1816', 'Производство рабочей одежды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1820', 'Выделка и крашение меха; производство изделий из натурального меха');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1821', 'Выделка и крашение меха');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1822', 'Производство изделий из натурального меха');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1900', 'Дубление и выделка кожи; производство чемоданов, сумок, шорно-седельных изделий и обуви');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1910', 'Дубление и выделка кожи; производство чемоданов, сумок, шорно-седельных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1911', 'Дубление и выделка кожи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1912', 'Производство чемоданов, сумок и аналогичных изделий кожгалантереи, шорно-седельных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1920', 'Производство обуви');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1921', 'Производство кожаной обуви');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1922', 'Производство резиновой обуви');
INSERT INTO REFACTIV (COD, NAME) VALUES ('1923', 'Производство спортивной обуви');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2000', 'Производство древесины, деревянных и пробковых изделий, кроме мебели; изделий из соломки и плетенки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2010', 'Производство лесопильное и строгальное');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2020', 'Производство изделий из дерева, пробки, соломки и плетенки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2021', 'Производство листовой фанеры; клееной фанеры, ламинированной плиты, древесно-стружечной плиты');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2022', 'Производство деревянных строительных конструкций и деталей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2023', 'Производство деревянной тары');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2029', 'Производство деревянных изделий прочих; производство изделий из пробки, соломки и плетенки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2100', 'Целлюлозно-бумажное производство и производство изделий из бумаги и картона');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2110', 'Производство целлюлозы, бумаги, картона и изделий из них');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2111', 'Производство целлюлозы, массы древесной и бумаги');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2112', 'Производство гофрированной бумаги, картона, бумажной и картонной тары');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2113', 'Производство бумаги для технических целей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2200', 'Издательское дело, полиграфическая промшленность и воспроизведение печатных материалов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2210', 'Издательское дело');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2211', 'Издание книг, брошюр, нотных сборников и прочих публикаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2212', 'Издание газет, журналов и периодических публикаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2213', 'Издание материалов, записанных на технических носителях');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2220', 'Полиграфическое исполнение и услуги, связанные с полиграфическим исполнением');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2221', 'Полиграфическое исполнение');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2222', 'Услуги, связанные с полиграфическим исполнением');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2230', 'Воспроизводство записанных материалов и услуги, связанные с воспроизводством записанных материалов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2231', 'Воспроизводство записанных материалов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2232', 'Услуги, связанные с воспроизводством записанных материалов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2300', 'Коксо-химическое производство, пр-во продукции нефтеперегонки, радиоактивных веществ и продукции на их основе');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2310', 'Производство продукции коксовых печей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2320', 'Производство продукции нефтеперегонки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2330', 'Производство радиоактивных веществ, топливных элементов и источников радиоактивного излучения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2331', 'Производство природного урана и его соединений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2332', 'Производство радиоактивных элементов и изотопов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2400', 'Производство продукции химического синтеза');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2410', 'Производство основных химических веществ');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2411', 'Производство основных химических веществ, кроме удобрений и азотных соединений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2412', 'Производство удобрений и азотных соединений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2413', 'Производство пластмасс в первичных формах и синтетического каучука');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2420', 'Производство химических продуктов прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2421', 'Производство пестицидов и агрохимических продуктов прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2422', 'Производство красок, лаков и аналогичных покрытий, типографской краски и мастик');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2423', 'Производство фармацевтических и лекарственных препаратов из растительных продуктов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2424', 'Производство мыла и моющих средств, чистящих и полирующих препаратов, парфюмерной и косметической продукции');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2430', 'Производство волокон и нитей химических');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2500', 'Производство резиновых и пластмассовых изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2510', 'Производство резиновых изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2511', 'Производство резиновых покрышек и камер, нарезка и восстановление резиновых покрышек');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2520', 'Производство полимерных смол, материалов и пластмассовых изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2521', 'Производство материалов из пластмасс');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2522', 'Производство изделий из пластмасс');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2523', 'Производство стеклопластиков');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2524', 'Производство тары из пластмасс');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2525', 'Производство пенопластов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2600', 'Производство неметаллических минеральных продуктов прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2610', 'Производство стекла и изделий из стекла');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2611', 'Производство необработанного плоского стекла и изделий из стекла прочих, применяемых в строительстве');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2612', 'Производство обработанного, литого, прокатанного, тянутого или выдутого стекла в листах, со шлифован. поверхн.');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2613', 'Производство изделий из упрочненного, безосколочного, закаленного и травленого стекла; изделий оптики');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2614', 'Производство стекловолокна и изделий из него');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2615', 'Производство стеклянной тары, включая бутылки, бутыли, банки, пузырьки, флаконы и закупоривающие средства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2616', 'Производство стеклянных хозяйственно-бытовых изделий и изделий для интерьеров');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2617', 'Производство стеклянных изделий для осветительной аппаратуры, копировального оборудования и часов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2618', 'Производство химической и лабораторной посуды из стекла');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2619', 'Производство стекла и изделий из стекла для электротехники, электровакуумных и оптических приборов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2690', 'Производство неметаллических минеральных продуктов, не включенных в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2691', 'Производство нестроительных и неогнеупорных керамических изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2692', 'Производство огнеупорных керамических изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2693', 'Производство керамических строительных неогнеупорных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2694', 'Производство цемента, извести, штукатурки, гипса');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2695', 'Производство изделий из бетона, цемента и гипса');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2696', 'Резка, фасонирование и отделка камня');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2700', 'Производство металлургическое');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2710', 'Производство чугуна и стали');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2711', 'Производство первичных материалов черной металлургии');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2712', 'Производство проката черных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2713', 'Производство изделий дальнейшего передела из проката черных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2714', 'Производство металлоизделий общепромышленного назначения (метизов) из черных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2715', 'Производство стальных труб');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2716', 'Производство металлопродукции прочей из черных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2720', 'Производство благородных и цветных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2721', 'Производство цветных, благороднх, редких металлов и их сплавов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2722', 'Производство порошков, пудр, паст, крупки благородных и цветных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2723', 'Производство проката легких цветных металлов и их сплавов (алюминий, магний, титан)');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2724', 'Производство проката тяжелых, благородных и редкоземельных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2725', 'Производство твердосплавной продукции');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2726', 'Производство металлоизделий общепромышленного назначения из цветных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2730', 'Производство металлического литья');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2731', 'Производство стального и чугунного литья');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2732', 'Производство цветного литья');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2800', 'Производство металлообрабатывающее, кроме производства машин и оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2810', 'Производство строительных металлических изделий, цистерн, резервуаров и паровых котлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2811', 'Производство строительных металлических изделий и их деталей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2812', 'Производство цистерн, резервуаров и металлических емкостей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2813', 'Производство паровых котлов, кроме бойлеров для центрального отопления, и составных частей к ним');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2890', 'Производство металлических изделий прочих; услуги производителям готовых металлических изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2891', 'Ковка, прессование, штамповка и профилирование металла; порошковая металлургия');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2892', 'Обработка и покрытие металлов; общее машиностроение');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2893', 'Производство ручных инструментов и скобяных изделий общего применения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2894', 'Производство инструмента режущего для металлообрабатывающих и деревообрабатывающих станков');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2895', 'Производство инструмента алмазного, из сверхтвердых материалов, инструмента и материалов абразивных');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2896', 'Производство оснастки технологической для машиностроения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2897', 'Производство санитарно-технического оборудования из металла');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2900', 'Производство машин и оборудования, не включенных в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2910', 'Производство машин, оборудования и комплектующих изделий общемашиностроительного применения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2911', 'Производство двигателей и турбин, кроме авиационных, автомобильных и мотоциклетных двигателей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2912', 'Производство насосов, компрессорного оборудоваия, пробок и клапанов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2913', 'Производство подшипников качения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2914', 'Производство термического и электротермического оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2915', 'Производство грузоподъемного и такелажного оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2916', 'Производство устройств гидро- и пневмоавтоматики');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2918', 'Производство тракторов и двигателей к ним');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2920', 'Производство специальных машин и оборудования для различных отраслей экономики');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2921', 'Производство машин и оборудования для сельского хозяйства и лесоводства, кроме тракторов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2922', 'Производство станков');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2923', 'Производство машин и оборудования для металлургии');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2924', 'Производство машин и оборудования для горнодобывающей промышленности, разработки карьеров и строительства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2925', 'Производство машин и оборудования для обработки пищевых продуктов, напитков и табачных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2926', 'Производство машин и оборудования для текстильной, швейной и кожевенной промышленности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2927', 'Производство оружия и военного снаряжения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2928', 'Производство оборудования нефтепромыслового и бурового геологоразведочного');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2930', 'Производство бытовых приборов, не включенных в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2940', 'Производство оборудования специализированного технологического, не включенного в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2941', 'Производство оборудования технологического для лесозаготовительной и торфяной промышленности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2942', 'Производство оборудования технологического для стекольно-ситалловой промышленности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2943', 'Производство оборудования специализированного технологического для производства электрических ламп');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2944', 'Производство машин и оборудования для коммунального хозяйства; производство пожарной техники');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2945', 'Производство оборудования технологического для предприятий торговли, общественного питания и пищеблоков');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2946', 'Производство оборудования специализированного технологического для медицинской промышленности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('2947', 'Производство машин и оборудования строительно-отделочного, строительно-монтажного');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3000', 'Производство канцелярских, бухгалтерских и электронно-вычислительных машин');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3010', 'Производство средств механизации и автоматизации управленческого и инженерно-технического труда');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3020', 'Производство электронно-вычислительной техники');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3100', 'Производство электрических машин и аппаратуры, не включенных в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3110', 'Производство электродвигателей, генераторов и трансформаторов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3120', 'Производство электрораспределителей и контрольной аппаратуры');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3130', 'Производство изолированного провода и кабеля');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3131', 'Производство силовых проводов и кабелей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3132', 'Производство проводов и кабелей для управления, контроля и систем связи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3133', 'Производство монтажных и обмоточных проводов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3134', 'Производство оптоволоконных кабелей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3140', 'Производство источников автономного электропитания');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3141', 'Производство аккумуляторов, первичных элементов и батарей из них');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3150', 'Производство электроламп и осветительного оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3200', 'Производство оборудования и аппаратуры для радио, телевидения и связи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3210', 'Производство электронных ламп, трубок и электронных компонентов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3211', 'Производство дискретных электронных компонентов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3212', 'Производство интегральных микросхем');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3213', 'Производство изделий квантовой электроники');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3219', 'Производство печатных плат, магнитопроводов и магнитов, комплектующих электрорадиоизделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3220', 'Производство теле- и радиопередатчиков и аппаратуры для кабельной телефонной и телеграфной связи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3221', 'Производство средств радиосвязи, радиовещания и телевидения; радиолокационных и навигационных средств');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3222', 'Производство средств кабельной связи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3230', 'Производство теле- и радиоприемников и сопутствующих потребительских товаров');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3300', 'Производство медицинских приборов, точных и оптических инструментов, часов и приборов времени');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3310', 'Производство медицинских приборов и инструментов; приборов для измерения, поверки, навигации');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3311', 'Производство медицинского, хирургического оборудования и ортопедических приспособлений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3312', 'Производство средств измерения общего применения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3313', 'Производство оборудования для контроля технологических процессов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3314', 'Производство испытательного оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3315', 'Производство приборов для научных исследований');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3320', 'Производство оптических приборов, фото- и кинооборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3321', 'Производство оптических инструментов и приборов общепромышленного и научного применения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3322', 'Производство фото- и киноаппаратуры, аппаратуры для измерения характеристик и обработки фото- и киноматериалов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3330', 'Производство часов и приборов времени прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3400', 'Производство автомобилей, прицепов и полуприцепов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3410', 'Производство автомобилей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3420', 'Производство корпусов (кузовные работы) для автомобилей; производство прицепов и полуприцепов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3430', 'Производство автомобильных двигателей, деталей и принадлежностей для автомобилей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3440', 'Производство гаражного и автозаправочного оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3500', 'Производство транспортных средств прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3510', 'Строительство и ремонт судов и лодок');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3511', 'Строительство и ремонт судов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3512', 'Строительство и ремонт судов спортивных, туристических и прогулочных');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3513', 'Производство судового оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3520', 'Производство железнодорожных, трамвайных локомотивов, рельсового подвижного состава, оборудования и деталей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3530', 'Производство воздушных и космических летательных аппаратов; оборудования и деталей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3531', 'Производство воздушных летательных аппаратов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3532', 'Производство космических летательных аппаратов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3533', 'Производство оборудования и деталей для летательных аппаратов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3590', 'Производство транспортных средств, не включенных в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3591', 'Производство мотоциклов, мотороллеров и мопедов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3592', 'Производство велосипедов и инвалидных колясок');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3600', 'Производство мебели; производство готовых изделий, не включенных в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3610', 'Производство мебели');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3611', 'Производство бытовой мебели');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3612', 'Производство специальной мебели');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3613', 'Производство составных частей мебели');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3614', 'Производство мебельной фурнитуры');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3690', 'Производство готовых изделий, не включенных в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3691', 'Производство ювелирных изделий и смежных товаров');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3692', 'Производство музыкальных инструментов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3693', 'Производство спортивных товаров');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3694', 'Производство игр и игрушек из различных материалов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3695', 'Производство учебно-наглядных пособий и учебного оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3696', 'Производство оборудования, инвентаря и принадлежностей для зрелищных предприятий и учреждений культуры');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3697', 'Производство вспомогательных изделий для легкой промышленности и предметов хозяйственно-бытового назначения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3698', 'Производство изделий художественных промыслов, произведений искусства и предметов коллекционирования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3700', 'Сбор и вторичная переработка отходов и лома в форму, пригодную для использования в качестве нового сырья');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3710', 'Сбор и вторичная переработка металлических отходов и лома');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3711', 'Сбор и вторичная переработка черных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3712', 'Сбор и вторичная переработка цветных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3713', 'Сбор и вторичная переработка благородных металлов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3720', 'Сбор и вторичная переработка неметаллических отходов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3721', 'Сбор и вторичная переработка отходов пищевой и табачной промышленности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3722', 'Сбор и вторичная переработка отходов текстильной и трикотажной промышленности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('3723', 'Сбор и вторичная переработка отходов кожевенной, резино-технич., целлюлозно-бумажн. и деревообрабат.промышл.');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4000', 'Снабжение электроэнергией, газом, паром и горячей водой');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4010', 'Производство, сбор и распределение электроэнергии');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4020', 'Производство газа; распределение газообразного топлива по трубопроводам');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4030', 'Снабжение паром и горячей водой');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4100', 'Сбор, очистка и распределение воды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4110', 'Очистка воды, производство льда и холода');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4500', 'Строительство');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4510', 'Подготовка строительного участка');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4520', 'Строительство завершенных зданий и сооружений или их частей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4521', 'Строительство зданий и сооружений топливно-энергетических, металлургических и нефтехимических предприятий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4522', 'Строительство зданий и сооружений машиностроительных предприятий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4523', 'Строительство зданий и сооружений предприятий лесной промышл., деревообрабат., целлюлозно-бумажн.');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4524', 'Строительство зданий и сооружений предприятий легкой, пищевой,микробиологич.,мукомольной и мед.промышлен.');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4525', 'Строительство зданий и сооружений сельскохозяйственных предприятий и предприятий лесного хозяйства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4526', 'Строительство зданий и сооружений предприятий строительной индустрии, транспорта и связи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4527', 'Строительство зданий и сооружений торговли, общественного питания, жилищно-коммунального хозяйства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4528', 'Строительство зданий и сооружений предприятий здарвоохранения, науки и научного обслуживания, образования, кул');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4529', 'Строительство зданий и сооружений для государственного управления, обороны, государственной безопасности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4530', 'Оборудование зданий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4540', 'Завершение строительства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4550', 'Аренда оборудования с оператором для строительства и сноса зданий и сооружений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4560', 'Оформление проектной документации и подготовка технико-экономических обоснований по строительной продукции');
INSERT INTO REFACTIV (COD, NAME) VALUES ('4590', 'Производство строительных материалов и комплектующих изделий, не включенных в другие группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5000', 'Продажа, техническое обслсуживание и ремонт автомобилей и мотоциклов; розничная продажа горючего');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5010', 'Продажа автомобилей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5020', 'Техническое обслуживание и ремонт автомобилей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5030', 'Продажа деталей и принадлежностей для автомобилей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5040', 'Продажа, техническое обслуживание и ремонт мотоциклов; продажа деталей и принадлежностей для мотоциклов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5050', 'Розничная торговля горючим для транспортных средств с двигателями внутреннего сгорания');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5100', 'Оптовая и коммисионная торговля, кроме торговли автомобилями и мотоциклами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5110', 'Комиссионная торговля');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5120', 'Оптовая торговля сельскохозяйственным сырьем, живыми животными, пищевыми продуктами и табачными изделиями');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5121', 'Оптовая торговля сельскохозяйственным сырьем и животными продуктами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5122', 'Оптовая торговля пищевыми продуктами, напитками и табачными изделиями');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5130', 'Оптовая торговля бытовыми товарами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5131', 'Оптовая торговля текстильными изделиями, одеждой и обувью');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5132', 'Оптовая торговля бытовыми приборами, изделиями и оборудованием');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5133', 'Оптовая торговля фармацевтическими товарами и косметикой');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5140', 'Оптовая торговля промежуточными продуктами, кроме сельскохозяйственных, отходами и ломом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5141', 'Оптовая торговля твердым, жидким и газообразным топливом и смежной продукцией');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5142', 'Оптовая торговля металлическими рудами и металлами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5143', 'Оптовая торговля строительными материалами, скобяными изделиями, водопроводным оборудованием');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5150', 'Оптовая торговля машинами, оборудованием и производственными материалами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5190', 'Оптовая торговля прочая');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5200', 'Розничная торговля, кроме торговли автомобилями и мотоциклами; ремонт бытовых товаров');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5210', 'Розничная торговля неспециализированная');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5220', 'Розничная торговля продовольственными товарами в специализированных магазинах');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5221', 'Розничная торговля овощами и фруктами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5222', 'Розничная торговля молочными продуктами и яйцами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5223', 'Розничная торговля мясом (в том числе мясом домашней птицы) и мясными продуктами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5224', 'Розничная торговля рыбой и морскими продуктами прочими, продукцией, изготовленной из них');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5225', 'Розничная торговля хлебом и мучными кондитерскими изделиями');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5226', 'Розничная торговля сахарными кондитерскими изделиями');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5227', 'Розничная торговля напитками, потребляемыми не на месте покупки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5228', 'Розничная торговля табачными изделиями');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5230', 'Розничная торговля непродовольственными товарами в специализированных магазинах');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5231', 'Розничная торговля фармацевтическими, медицинскими и косметическими товарами, туалетными принадлежностями');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5232', 'Розничная торговля текстильными изделиями, одеждой, обувью и изделиями из кожи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5233', 'Розничная торговля бытовыми приборами, изделиями и оборудованием');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5234', 'Розничная торговля скобяными изделиями, красками и стеклом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5235', 'Розничная торговля оборудованием для офисов, канцелярскими принадлежностями, книгами и газетами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5240', 'Розничная торговля подержанными товарами в магазинах');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5250', 'Розничная торговля не в магазинах');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5251', 'Розничная торговля через фирмы, выполняющие заказы по почте');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5252', 'Розничная торговля через палатки и рынки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5260', 'Ремонт бытовых товаров и предметов личного пользования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5261', 'Ремонт обуви, изделий из кожи и меха');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5262', 'Ремонт бытовых электроприборов и бытовой радиоэлектронной аппаратуры');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5263', 'Ремонт часов и ювелирных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5264', 'Ремонт одежды и домашних текстильных изделий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5500', 'Деятельность гостиниц и ресторанов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5510', 'Деятельность гостиниц, мотелей, площадок для кемпингов и прочих мест краткосрочного проживания');
INSERT INTO REFACTIV (COD, NAME) VALUES ('5520', 'Деятельность ресторанов, баров и столовых');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6000', 'Транспорт сухопутный; транспортировка по трубопроводам');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6010', 'Транспорт железнодорожный');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6020', 'Транспорт сухопутный');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6021', 'Транспорт автодорожный, подчиняющийся расписанию');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6022', 'Транспорт автодорожный, не подчиняющийся расписанию');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6023', 'Фрахтовые перевозки автодорожным транспортом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6024', 'Деятельность прочих видов сухопутного транспорта, таких как фуникулеры и воздушные канатные дороги');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6030', 'Транспортировка грузов по трубопроводам');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6100', 'Водный транспорт');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6110', 'Морской водный транспорт');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6120', 'Внутренний водный транспорт (речной и озерный)');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6200', 'Воздушный транспорт');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6210', 'Воздушный транспорт, подчиняющийся расписанию');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6220', 'Воздушный транспорт, не подчиняющийся расписанию');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6230', 'Транспортировка пассажиров и грузов в космическом пространстве');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6300', 'Транспортная деятельность вспомогательная и дополнительная; деятельность бюро путешествий и экскурсий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6310', 'Транспортировка и хранение грузов; деятельность в области туризма и экскурсий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6311', 'Транспортная обработка грузов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6312', 'Хранение и складирование грузов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6314', 'Деятельность бюро путешествий, туристских агентов и экскурсионных бюро');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6400', 'Почта и система связи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6410', 'Почтовая и курьерская деятельность');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6411', 'Деятельность национальных почт');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6412', 'Курьерская деятельность');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6420', 'Связь для обеспечения передачи звука, изображения и данных');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6500', 'Финансовое посредничество, кроме страхования и пенсионного обеспечения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6510', 'Денежное посредничество');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6511', 'Центральный банк');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6512', 'Коммерческие банки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6600', 'Страхование и пенсионное обеспечение, кроме обязательного социального страхования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6610', 'Страхование жизни и пенсионное обеспечение');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6611', 'Страхование жизни');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6612', 'Пенсионное обеспечение');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6613', 'Страхование, кроме страхования жизни');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6700', 'Деятельность, вспомогательная по отношению к финансовому посредничеству');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6710', 'Деятельность, вспомогательная к финансовому посредничеству, кроме страхования и пенсионного обеспечения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6711', 'Управление финансовыми рынками');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6712', 'Биржевые операции с фондовыми ценностями, кроме услуг коммерческих банков');
INSERT INTO REFACTIV (COD, NAME) VALUES ('6720', 'Деятельность, вспомогательная по отношению к страхованию и пенсионному обеспечению');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7000', 'Операции с недвижимым имуществом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7010', 'Операции с недвижимым имуществом, собственным или арендуемым');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7020', 'Деятельность вспомогательная по операциям с недвижимым имуществом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7100', 'Лизинг или аренда машин и оборудования без оператора; аренда бытовых товаров и предметов личного пользования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7110', 'Лизинг или аренда транспортных средств без оператора');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7111', 'Лизинг или аренда сухопутных транспортных средств без водителя');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7112', 'Лизинг или аренда водных транспортных средств без экипажа');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7113', 'Лизинг или аренда воздушных транспортных средств без экипажа');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7120', 'Лизинг или аренда прочих машин и оборудования без оператора');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7121', 'Лизинг или аренда сельскохозяйственных машин и оборудования без оператора');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7122', 'Лизинг или аренда машины и оборудования для производственного и гражданского строительства без оператора');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7123', 'Лизинг или аренда машин и оборудования для офисов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7200', 'Деятельность, связанная с компьютерами');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7210', 'Консультации по компьютерным комплексам технических средств');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7220', 'Консультации по программному обеспечению');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7230', 'Консультации по информационному обеспечению и обработке данных');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7240', 'Разработка автоматизированных информационных систем, систем для научных исследований на основе баз данных');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7241', 'Разработка автоматизированных информационных систем');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7242', 'Разработка автоматизированных систем для научных исследований');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7243', 'Разработка автоматизированных систем проектирования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7244', 'Разработка автоматизированных систем управления');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7245', 'Разработка диагностических и экспертных систем');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7250', 'Техническое обслуживание и ремонт оргтехники для офисов, вычислительных машин и периферийного оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7260', 'Разработка системных и прикладных программных средств');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7300', 'Исследования и разработки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7310', 'Исследования и разработки в области естественных и технических наук');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7320', 'Исследования и разработки в областях общественных и гуманитарных наук');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7400', 'Коммерческая и техническая деятельность прочая');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7410', 'Право, составление счетов, бухучет и ревизия; консультации по налогообложению; исследование рынка');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7411', 'Право');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7412', 'Составление счетов, бухгалтерский учет и ревизии, консультации по вопросам налогообложения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7413', 'Исследование конъюнктуры рынка; деятельность по выявлению общественного мнения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7414', 'Консультации по вопросам управления коммерческой деятельностью');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7420', 'Архитектура, строительство; испытания и анализ; сертификация, аттестация; метрология; стандартизация; геология');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7421', 'Архитектура и гражданское и промышленное строительство и связанные с этим технические консультации');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7422', 'Технические испытания и анализ');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7423', 'Сертификация продукции и аттестация производства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7424', 'Метрологические службы');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7425', 'Стандартизация');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7426', 'Гидрометеорологические исследования и прогнозирование погоды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7427', 'Геологические исследования и разведка недр');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7430', 'Реклама');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7440', 'Экспертиза проектов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7490', 'Деятельность коммерческая прочая, не включенная в группировки');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7491', 'Найм рабочей силы и обеспечение персоналом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7492', 'Расследование и обеспечение безопасности частных лиц и имущества');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7493', 'Чистка и уборка зданий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7494', 'Фотография');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7495', 'Упаковка');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7500', 'Деятельность в области государственного управления и обороны; в области обязательного социального страхования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7510', 'Деятельность по управлению государством в области формирования социально-экономической политики общества');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7511', 'Деятельность по всем аспектам в области управления на государственном уровне');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7512', 'Регулирование деятельности учреждений, обеспечивающих мед. обслуживание, образование, культуру');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7513', 'Регулирование и содействие развитию более эффективной коммерческой деятельности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7514', 'Деятельность по предоставлению вспомогательных услуг правительству в целом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7520', 'Предоставление услуг обществу в целом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7521', 'Деятельность по иностранным делам');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7522', 'Оборонная деятельность');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7523', 'Охрана общественного порядка и безопасность');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7524', 'Сбор и анализ статистических данных по социально-экономическому развитию общества');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7525', 'Защита окружающей среды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('7530', 'Обязательное социальное страхование');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8000', 'Образование');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8010', 'Начальное образование');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8020', 'Среднее образование');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8021', 'Общее среднее образование');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8022', 'Среднее профессиональное образование');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8030', 'Высшее образование');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8040', 'Непрерывное образование для взрослых');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8500', 'Здравоохранение и оказание социальных услуг');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8510', 'Охрана здоровья человека');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8511', 'Больницы и специализированные лечебные центры');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8512', 'Врачебная и зубоврачебная амбулаторная практика');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8513', 'Санитарно-профилактические учреждения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8514', 'Санаторно-курортная и оздоровительная деятельность');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8520', 'Ветеринарная деятельность');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8530', 'Социальные услуги');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8531', 'Предоставление социальных услуг с обеспечением проживания');
INSERT INTO REFACTIV (COD, NAME) VALUES ('8532', 'Предоставление социальных услуг без обеспечения проживания');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9000', 'Канализация и удаление отходов, санитарная обработка и аналогичные виды деятельности');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9100', 'Деятельность членских организаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9110', 'Деятельность коммерческих, предпринимательских и профессиональных организаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9111', 'Деятельность коммерческих и предпринимательских организаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9112', 'Деятельность профессиональных организаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9120', 'Деятельность профсоюзов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9190', 'Деятельность членских организаций прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9191', 'Деятельность религиозных организаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9192', 'Деятельность политических организаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9193', 'Деятельность общественных организаций');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9200', 'Деятельность в области организации распространения информации, культуры, спорта, отдыха и развлечений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9210', 'Деятельность в области кино, радио, телевидения, театра и прочих видах искусства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9211', 'Производство и распространение кино- и видеофильмов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9212', 'Демонстрация кинофильмов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9213', 'Деятельность в области радио и телевидения');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9214', 'Деятельность в области драматического искусства, музыки, живописи, литературы и видах искусства прочих');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9220', 'Деятельность агентов печати и других организаций по распространению информации');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9221', 'Деятельность по распространению информации на основе баз данных и знаний с использованием вычислительных сетей');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9222', 'Деятельность по распространению оперативной коммерческой информации');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9223', 'Деятельность по распространению оперативной информации о погоде и состоянию окружающей среды');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9230', 'Деятельность библиотек, архивов, музеев и аналогичная деятельность в области культуры');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9231', 'Деятельность библиотек и архивов и деятельность культурно-просветительных учреждений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9232', 'Деятельность музеев, охрана исторических памятников, мест и зданий');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9233', 'Деятельность ботанических садов, зоопарков и заповедников');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9240', 'Спортивная деятельность и деятельность по организации отдыха и развлечений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9241', 'Спортивная деятельность');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9300', 'Деятельность в области жилищно-коммунального хозяйства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9310', 'Деятельность по предоставлению жилищно-коммунальных услуг');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9311', 'Деятельность по стирке, чистке и окраске текстильных изделий и изделий из меха');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9312', 'Деятельность парикмахерских, салонов и лечебных косметических учреждений');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9313', 'Деятельность по организации похорон и связанные с этим ритуальные услуги');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9314', 'Деятельность по ремонту жилищ (квартир, домов) и строительству индивидуального жилья');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9400', 'Деятельность в обрабатывающей промышленности, осуществляемая по частным заказам');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9430', 'Ремонт металлических изделий, машин и оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9431', 'Ремонт готовых металлических изделий, кроме машин и оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9432', 'Ремонт машин и оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9433', 'Ремонт счетных, электронно-вычислительных машин и оборудования для офисов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9434', 'Ремонт электрических машин и электротехнического оборудования');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9435', 'Ремонт радиоэлектронной аппаратуры для радио, телевидения и связи');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9436', 'Ремонт медицинских приборов, точного и оптического инструмента, наручных и прочих часов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9437', 'Ремонт автомобилей, прицепов и полуприцепов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9438', 'Ремонт таракторов, машин и оборудования для сельского хозяйства');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9440', 'Снабжение электроэнергией, газом, паром и горячей водой');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9460', 'Техническое обслуживание машин и оборудования (в том числе гарантийное)');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9500', 'Деятельность частных домашних хозяйств с наемным обслуживанием');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9510', 'Деятельность по предоставлению услуг для ведения частных домашних хозяйств с наемным обслуживающим персоналом');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9900', 'Деятельность экстерриториальных организаций и органов');
INSERT INTO REFACTIV (COD, NAME) VALUES ('9910', 'Деятельность по предоставлению услуг экстерриториальных организаций и органов');
GO

SET NOCOUNT OFF;

