USE BestDatabaseBerkoz;
GO

SET NOCOUNT ON;

INSERT INTO REFFORMORG (COD, NAME) VALUES ('00', '*Неопределенная');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('39', 'ЮРИДИЧЕСКИЕ ЛИЦА, ЯВЛЯЮЩИЕСЯ КОММЕРЧЕСКИМИ ОРГАНИЗАЦИЯМИ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('40', 'Унитарные предприятия');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('41', 'Унитарные предприятия, основанные на праве оперативного управления');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('42', 'Унитарные предприятия, основанные на праве хозяйственного ведения');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('44', 'ПРЕДПРИЯТИЯ ОБЩЕСТВЕННЫХ И РЕЛИГИОЗНЫХ ОРГАНИЗАЦИЙ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('45', 'ПРЕДПРИЯТИЯ ПОТРЕБИТЕЛЬСКОЙ КООПЕРАЦИИ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('46', 'ИНДИВИДУАЛЬНЫЕ (СЕМЕЙНЫЕ) ЧАСТНЫЕ ПРЕДПРИЯТИЯ (С ПРИВЛЕЧЕНИЕМ НАЕМНОГО ТРУДА)');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('47', 'Открытые акционерные общества');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('48', 'Хозяйственные товарищества и общества');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('49', 'ТОВАРИЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('50', 'СМЕШАННЫЕ ТОВАРИЩЕСТВА');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('51', 'Полные товарищества');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('52', 'Производственные кооперативы');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('53', 'Крестьянские (фермерские) хозяйства');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('54', 'КОЛХОЗЫ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('55', 'СОВХОЗЫ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('56', 'МЕЖХОЗЯЙСТВЕННЫЕ ПРЕДПРИЯТИЯ (ОРГАНИЗАЦИИ)');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('57', 'АРЕНДНЫЕ ПРЕДПРИЯТИЯ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('60', 'Акционерные общества');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('61', 'АРЕНДНЫЕ ПРЕДПРИЯТИЯ В ФОРМЕ АКЦИОНЕРНОГО ОБЩЕСТВА ЗАКРЫТОГО ТИПА,ТОВАРИЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('62', 'АРЕНДНЫЕ ПРЕДПРИЯТИЯ В ФОРМЕ СМЕШАННОГО ТОВАРИЩЕСТВА');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('64', 'Товарищества на вере');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('65', 'Общества с ограниченной ответственностью');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('66', 'Общества с дополнительной ответственностью');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('67', 'Закрытые акционерные общества');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('68', 'Дочерние унитарные предприятия');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('69', 'ДРУГИЕ ПРЕДПРИЯТИЯ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('70', 'ЮРИДИЧЕСКИЕ ЛИЦА, ЯВЛЯЮЩИЕСЯ НЕКОММЕРЧЕСКИМИ ОРГАНИЗАЦИЯМИ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('74', 'ОБЪЕДИНЕНИЯ ПРЕДПРИЯТИЙ В ФОРМЕ АКЦИОНЕРНОГО ОБЩЕСТВА ЗАКРЫТОГО ТИПА,ТОВАРИЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('75', 'ОБЪЕДИНЕНИЯ ПРЕДПРИЯТИЙ В ФОРМЕ СМЕШАННОГО ТОВАРИЩЕСТВА');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('76', 'Садоводческие, огороднические или дачные некоммерческие товарищества');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('77', 'Ассоциации крестьянских (фермерских) хозяйств');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('78', 'Органы общественной самодеятельности');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('79', 'Финансово-промышленные группы');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('80', 'Территориальные общественные самоуправления');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('81', 'Учреждения');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('82', 'Государственные корпорации');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('83', 'Общественные и религиозные организации (объединения)');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('84', 'Общественные движения');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('85', 'Потребительские кооперативы');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('87', 'Простые товарищества');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('88', 'Фонды');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('89', 'Прочие некоммерческие организации');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('90', 'Представительства и филиалы');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('91', 'ИНДИВИДУАЛЬНЫЕ ПРЕДПРИНИМАТЕЛИ');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('92', 'Паевые инвестиционные фонды');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('93', 'Объединения юридических лиц (ассоциации и союзы)');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('94', 'Товарищества собственников жилья');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('96', 'Некоммерческие партнерства');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('97', 'Автономные некоммерческие организации');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('98', 'Иные неюридические лица');
INSERT INTO REFFORMORG (COD, NAME) VALUES ('99', 'ОРГАНИЗАЦИИ БЕЗ ПРАВ ЮРИДИЧЕСКОГО ЛИЦА');

INSERT INTO REFTYPEORG (COD, NAME) VALUES ('000', '*Неопределенный');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('001', 'Предприятие');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('002', 'Банк');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('003', 'Исследовательский институт');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('004', 'Клуб');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('005', 'Страховая компания');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('006', 'Биржа');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('007', 'Брокерская контора');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('008', 'Торговый дом');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('009', 'Предприятие АПК');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('010', 'Высшее учебное заведение');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('011', 'Техникум (колледж)');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('012', 'Школа (лицей, гимназия)');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('013', 'ПТУ (ТУ)');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('014', 'Дошкольное образовательное учреждение');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('015', 'Дошкольное специализированное учреждение');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('016', 'Среднее специализированное учреждение');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('017', 'Больница');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('018', 'Приют');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('019', 'Детский дом');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('020', 'Дом ребенка');
INSERT INTO REFTYPEORG (COD, NAME) VALUES ('021', 'Интернат');

INSERT INTO REFFORMPROP (COD, NAME) VALUES ('00', '*Неопределенная');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('10', 'РОССИЙСКАЯ СОБСТВЕННОСТЬ');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('11', 'Государственная собственность)');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('12', 'Федеральная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('13', 'Собственность субъектов Российской Федерации');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('14', 'Муниципальная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('15', 'Собственность общественных и религиозных организаций (объединений)');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('16', 'Частная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('17', 'Смешанная российская собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('18', 'Собственность российских граждан, постоянно проживающих за границей');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('19', 'Собственность потребительской кооперации');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('20', 'ИНОСТРАННАЯ СОБСТВЕННОСТЬ');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('21', 'Собственность международных организаций');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('22', 'Собственность иностранных государств');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('23', 'Собственность иностранных юридических лиц');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('24', 'Собственность иностранных граждан и лиц без гражданства');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('27', 'Смешанная иностранная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('30', 'СОВМЕСТНАЯ РОССИЙСКАЯ И ИНОСТРАННАЯ СОБСТВЕННОСТЬ');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('31', 'Совместная федеральная и иностранная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('32', 'Совместная собственность субъектов Российской Федерации и иностранная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('33', 'Совместная муниципальная и иностранная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('34', 'Совместная частная и иностранная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('35', 'Совместная собственность общественных и религиозных организаций (объединений) и иностранная собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('40', 'Смешанная российская собственность с долей государственной собственности');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('41', 'Смешанная российская собственность с долей федеральной собственности');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('42', 'Смешанная российская собственность с долей собственности субъектов Российской Федерации');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('43', 'Смешанная российская собственность с долями федеральной собственности и собственности субъектов Российской Федерации');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('49', 'Иная смешанная российская собственность');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('50', 'Собственность благотворительных организаций');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('51', 'Собственность политических общественных объединений');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('52', 'Собственность профессиональных союзов');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('53', 'Собственность общественных объединений');
INSERT INTO REFFORMPROP (COD, NAME) VALUES ('54', 'Собственность религиозных объединений');
GO

SET NOCOUNT OFF;
