use [BestDatabaseMorozov]
--Триггер
CREATE TRIGGER dbo.trigger3lab ON dbo.PEOPLE
AFTER INSERT, UPDATE
AS BEGIN
IF EXISTS(SELECT * FROM inserted WHERE BIRTHDAY>GETDATE())
BEGIN
RAISERROR ('Вы еще не родились',10,1);
ROLLBACK TRANSACTION;
END;
IF EXISTS(SELECT * FROM inserted WHERE (
BIRTHDAY<DATEADD(year, -100, GETDATE()) AND SEX LIKE '0')
OR (BIRTHDAY<DATEADD(year, -110, GETDATE()) AND SEX LIKE '1'))
BEGIN
RAISERROR ('Неправильная дата',10,1);
ROLLBACK TRANSACTION;
END;
END;
SET IDENTITY_INSERT dbo.PEOPLE ON ;
BEGIN TRANSACTION;
--Беркоз МА
INSERT INTO dbo.PEOPLE (NAME1, NAME2, NAME3, BIRTHDAY, SEX, CODMOTHER,
CODFATHER, CODOTHERHALF)
VALUES ('Иван', 'Иванович', 'Иванов', '3001-01-01', '0', NULL, NULL, NULL),('Михаил', 'Алексеевич', 'Беркоз', '2001-11-23', '0', NULL, NULL, NULL);
select * from people where BIRTHDAY = '2001-11-23';